### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by btmdave** [pm2-hive/pm2-server-monit#15]
We get warnings/error when starting up monit.  Running on node 0.12.7.
```
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
TypeError: Cannot read property 'replace' of undefined
    at /root/.pm2/node_modules/pm2-server-monit/lib/drive.js:23:35
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
```

**Comment by btmdave** [comment]
Here's the full trace:

```

    "at": 1441190448506,
    "data": {
        "stack": "TypeError: Cannot call method 'replace' of undefined\n    at probe.metric.name (/root/.pm2/node_modules/pm2-server-monit/lib/drive.js:23:36)\n    at ChildProcess.exithandler (child_process.js:662:7)\n    at ChildProcess.emit (events.js:98:17)\n    at maybeClose (child_process.js:766:16)\n    at Process.ChildProcess._handle.onexit (child_process.js:833:5)",
        "arguments": [
            "replace",
            null
        ],
        "type": "non_object_property_call",
        "message": "Cannot call method 'replace' of undefined"
    },
    "process": {
        "pm_id": 6,
        "name": "pm2-server-monit",
        "rev": null,
        "server": "worker06"
    },
    "created_at": 1441165117481,
    "updated_at": 1441190448506,
    "count": 53,
    "identifier": "1accf4d0eac390ac1a89c6a431f13328",
    "infected_servers": [
        "worker06"
    ],
    "timestamps": [
        1441165117481,
        1441165135745,
        1441165374883,
        1441165383078,
        1441176617400,
        1441176625596,
        1441176633774,
        1441189982223,
        1441189990448,
        1441190008712,
        1441190016919,
        1441190025129,
        1441190033329,
        1441190041519,
        1441190049717,
        1441190057906,
        1441190084388,
        1441190092597,
        1441190100827,
        1441190109031,
        1441190117239,
        1441190125440,
        1441190133647,
        1441190141849,
        1441190150043,
        1441190158244,
        1441190166462,
        1441190174670,
        1441190182864,
        1441190191075,
        1441190199271,
        1441190207496,
        1441190215716,
        1441190232149,
        1441190240365,
        1441190248577,
        1441190256779,
        1441190264981,
        1441190273185,
        1441190281381,
        1441190289590,
        1441190297794,
        1441190306003,
        1441190314207,
        1441190322413,
        1441190330624,
        1441190338827,
        1441190347040,
        1441190415603,
        1441190423831,
        1441190432063,
        1441190440288,
        1441190448506
    ],
    "commits": [],
    "servers": [
        "worker06"
    ],
    "show_detail": true
}
```

**Comment by alavit-d** [comment]
Hi,
We parse the result of the command `df -k` to retrieve information about your hard drive.
Could you execute it in command line and see if it outputs anything?

I will add error check for the next version of the module

**Comment by btmdave** [comment]
Yeah, `df -k` works

```
:~# df -k
Filesystem            1K-blocks         Used    Available Use% Mounted on
/dev/md0p1             49125768      4469532     42137732  10% /
none                          4            0            4   0% /sys/fs/cgroup
udev                   32940692            4     32940688   1% /dev
tmpfs                   6596876          844      6596032   1% /run
none                       5120            0         5120   0% /run/lock
none                   32984372            0     32984372   0% /run/shm
none                     102400            0       102400   0% /run/user
storage02:/storage 539645449984 316805194752 222840173312  59% /storage
```

**Comment by alavit-d** [comment]
I just pushed an updated version, to see if it solves your issue could you uninstall the module (`pm2 uninstall pm2-server-monit`) then git clone this repo, go into it and run `pm2 install .`?

**Comment by btmdave** [comment]
Nice works, just has this left:

`pm2-server-monit-12 (err): child_process: customFds option is deprecated, use stdio instead.`

**Comment by alavit-d** [comment]
Yep, corrected this as well. Will be updated on npm soon.

**Comment by alavit-d** [comment]
New version published

**Comment by u382514** [comment]
I installed via NPM last night (09/03) and received this error. Do we know when NPM will be updated?
