### ISSUE TITLE
pm2-server-monit fails to install on latest npm and node

### ISSUE THREAD

**Issue by bountyx** [pm2-hive/pm2-server-monit#17]
I tried to install pm2-server-monit with the following command:
```
pm2 install pm2-server-monit
```
It failed with the following error:
```
267 verbose stack Error: Invalid name: ".pm2"
267 verbose stack     at ensureValidName (/usr/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:331:15)
267 verbose stack     at Object.module.exports.fixNameField (/usr/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:210:5)
267 verbose stack     at /usr/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:32:38
267 verbose stack     at Array.forEach (native)
267 verbose stack     at normalize (/usr/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:31:15)
267 verbose stack     at thenCheckTop (/usr/lib/node_modules/npm/lib/install/validate-tree.js:58:3)
267 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
267 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
267 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
267 verbose stack     at thenValidateAllPeerDeps (/usr/lib/node_modules/npm/lib/install/validate-tree.js:46:3)
```

Here are my relevant system specs:
```
Distro:    Ubuntu 14.04.3 LTS @ 3.13.0-57-generic
Node: v4.1.1
Npm: 3.3.4
pm2: 0.15.7
```

**Comment by Unitech** [comment]
Tried with npm 3.5.5, it's a mess
