### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by dszymczuk** [pm2-hive/pm2-server-monit#19]
I had this error, when my server was overload (in 30 minutes I had 60 load).

```
TypeError: Cannot read property 'replace' of undefined
	at /root/.pm2/node_modules/pm2-server-monit/lib/drive.js:22:35
	at ChildProcess.exithandler (child_process.js:194:7)
	at emitTwo (events.js:87:13)
	at ChildProcess.emit (events.js:172:7)
	at maybeClose (internal/child_process.js:818:16)
	at Socket. (internal/child_process.js:319:11)
	at emitOne (events.js:77:13)
	at Socket.emit (events.js:169:7)
	at Pipe._onclose (net.js:469:12)
```

**Comment by alavit-d** [comment]
fixed thx to PR https://github.com/pm2-hive/pm2-server-monit/pull/22
