### ISSUE TITLE
No lsb_release on aws linux

### ISSUE THREAD

**Issue by PierrickP** [pm2-hive/pm2-server-monit#4]
pm2-server-monit fail on startup.

```
 /home/ec2-user/.pm2/node_modules/pm2-server-monit/lib/os.js:8
    var version = out.match(/[\n\r].*Release:\s*([^\n\r]*)/)[1];
                                                            ^
TypeError: Cannot read property '1' of null
    at /home/ec2-user/.pm2/node_modules/pm2-server-monit/lib/os.js:8:61
    at /home/ec2-user/.pm2/node_modules/pm2-server-monit/node_modules/shelljs/src/exec.js:138:7
    at ChildProcess.exithandler (child_process.js:751:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
```

I don't have `lsb_release` on amazon linux.

pm2 version : 0.14.0
node : v0.12.0

**Comment by PierrickP** [comment]
@Kyoshim your fixe are ok but on npm it's the 0.2.0 version who seem to be an older code base

**Comment by Kyoshim** [comment]
@PierrickP Hi, thanks for your feedback,
You can install the latest publish version with ```pm2 install pm2-server-monit```
