### ISSUE TITLE
OS Version error

### ISSUE THREAD

**Issue by adrian-ludwig** [pm2-hive/pm2-server-monit#5]
```
pm2-server-monit-22 (err):     at /home/users/app/.pm2/node_modules/pm2-server-monit/node_modules/shelljs/src/exec.js:138:7
pm2-server-monit-22 (err):     at ChildProcess.exithandler (child_process.js:758:5)
pm2-server-monit-22 (err):     at ChildProcess.emit (events.js:110:17)
pm2-server-monit-22 (err):     at maybeClose (child_process.js:1015:16)
pm2-server-monit-22 (err):     at Socket.<anonymous> (child_process.js:1183:11)
pm2-server-monit-22 (err):     at Socket.emit (events.js:107:17)
pm2-server-monit-22 (err):     at Pipe.close (net.js:485:12)
pm2-server-monit-22 (err): child_process: customFds option is deprecated, use stdio instead.
pm2-server-monit-22 (err): /home/users/bfapp/.pm2/node_modules/pm2-server-monit/lib/os.js:8
pm2-server-monit-22 (err):     var version = out.match(/[\n\r].*Release:\s*([^\n\r]*)/)[1];
pm2-server-monit-22 (err):                                                             ^
pm2-server-monit-22 (err): TypeError: Cannot read property '1' of null
pm2-server-monit-22 (err):     at /home/users/app/.pm2/node_modules/pm2-server-monit/lib/os.js:8:61
pm2-server-monit-22 (err):     at /home/users/app/.pm2/node_modules/pm2-server-monit/node_modules/shelljs/src/exec.js:138:7
pm2-server-monit-22 (err):     at ChildProcess.exithandler (child_process.js:758:5)
pm2-server-monit-22 (err):     at ChildProcess.emit (events.js:110:17)
pm2-server-monit-22 (err):     at maybeClose (child_process.js:1015:16)
pm2-server-monit-22 (err):     at Socket.<anonymous> (child_process.js:1183:11)
pm2-server-monit-22 (err):     at Socket.emit (events.js:107:17)
pm2-server-monit-22 (err):     at Pipe.close (net.js:485:12)
```

cat /etc/issue
CentOS release 6.6 (Final)
Kernel \r on an \m

uname -r
2.6.32-504.12.2.el6.x86_64

pm2 -v
0.14.1

node -v
v0.12.3

**Comment by adrian-ludwig** [comment]
The same as #4
