### ISSUE TITLE
Can't exec with shell node v4

### ISSUE THREAD

**Issue by f-hj** [pm2-hive/pm2-server-monit#51]
```
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:285:26)
    at ChildProcess.spawn (/usr/share/pm2/node_modules/pmx/node_modules/vxx/node_modules/continuation-local-storage/node_modules/async-listener/index.js:120:29)
    at exports.spawn (child_process.js:362:9)
    at Object.exports.execFile (child_process.js:151:15)
    at Object.exports.exec (child_process.js:111:18)
    at refreshMetrics (/home/florian/.pm2/node_modules/pm2-server-monit/lib/drive.js:10:6)
    at Object.init (/home/florian/.pm2/node_modules/pm2-server-monit/lib/drive.js:100:3)
    at /home/florian/.pm2/node_modules/pm2-server-monit/app.js:46:9
    at Object.PMX.initModule (/home/florian/.pm2/node_modules/pmx/lib/pmx.js:116:12)
```

```
$ node -v
v4.6.2
```

But work correctly if `{shell: true}` is not specified.
@vmarchaud @Unitech

**Comment by altras** [comment]
I'm having the same issue I guess:

```
$ node -v
v4.5.0
```

```
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:362:9)
    at Object.exports.execFile (child_process.js:151:15)
    at Object.exports.exec (child_process.js:111:18)
    at refreshMetrics (/home/node/.pm2/node_modules/pm2-server-monit/lib/drive.js:10:6)
    at Object.init (/home/node/.pm2/node_modules/pm2-server-monit/lib/drive.js:100:3)
    at /home/node/.pm2/node_modules/pm2-server-monit/app.js:46:9
    at Object.PMX.initModule (/home/node/.pm2/node_modules/pm2-server-monit/node_modules/pmx/lib/pmx.js:116:12)
    at Object.<anonymous> (/home/node/.pm2/node_modules/pm2-server-monit/app.js:14:5)
```

pm2-server-monit version `2.5.1`

**Comment by vmarchaud** [comment]
@altras Platform ? (unix/windows + the version)

**Comment by altras** [comment]
@vmarchaud thank you for the reminder.

```
$ uname -a
Linux debian 4.9.7-x86_64-linode80 #2 SMP Thu Feb 2 15:43:55 EST 2017 x86_64 GNU/Linux
```

what else do I need to provide :?

**Comment by vmarchaud** [comment]
@altras Nothing else i think, we will investigate thanks :)

**Comment by tdsticks** [comment]
Having the same issue here as well.  Other pm2 components are working fine, but the pm2-server-monit won't run.

> 6|pm2-serv |     at Object.init (/home/devadmin/.pm2/node_modules/pm2-server-monit/lib/drive.js: 100: 3)
> 6|pm2-serv |     at /home/devadmin/.pm2/node_modules/pm2-server-monit/app.js:46:9
> 6|pm2-serv |     at Object.PMX.initModule (/home/devadmin/.pm2/node_modules/pmx/lib/pmx.js:116:12)
> 6|pm2-serv |     at Object.<anonymous> (/home/devadmin/.pm2/node_modules/pm2-server-monit/app.js:14:5)
> 6|pm2-serv | TypeError: Bad argument

Linux 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

node -v
v4.4.3

pm2 -v
2.4.5

**Comment by znzp124900171** [comment]
@vmarchaud 
Same issue +1

**Comment by Gamec** [comment]
Same issue.

Node v4.2.6
pm2 v2.3.0

**Comment by jazz321254** [comment]
i use development branch but it not solve yet.
```
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:362:9)
    at Object.exports.execFile (child_process.js:151:15)
    at Object.exports.exec (child_process.js:111:18)
    at module.exports (/home/ecadmin/.pm2/node_modules/pm2-server-monit/lib/exec.js:15:6)
    at refreshMetrics (/home/ecadmin/.pm2/node_modules/pm2-server-monit/lib/drive.js:10:3)
    at Object.init (/home/ecadmin/.pm2/node_modules/pm2-server-monit/lib/drive.js:100:3)
    at /home/ecadmin/.pm2/node_modules/pm2-server-monit/app.js:46:9
    at Object.PMX.initModule (/home/ecadmin/.pm2/node_modules/pm2-server-monit/node_modules/pmx/lib/pmx.js:116:12)
```
Node v4.6.0
PM2 v2.6.1

**Comment by pakastin** [comment]
I have similar issue on one of our legacyish servers:
```
/root/.pm2/node_modules/pm2-server-monit/lib/mem.js:57
    lines = lines.filter(x => x !== '')
                           ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:94:21)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/.pm2/node_modules/pm2-server-monit/app.js:6:15)
    at Module._compile (module.js:460:26)
```

**Comment by f-hj** [comment]
New version (2.5.2) published. Try an update!

**Comment by pakastin** [comment]
Now works, thanks! 👌

**Comment by aivus** [comment]
I'm still getting this error on node `v4.7.0`

```
Module activated
┌──────────────────┬─────────┬────────────┬─────────┬─────────┬─────┬────────┬────────┐
│ Module           │ version │ target PID │ status  │ restart │ cpu │ memory │ user   │
├──────────────────┼─────────┼────────────┼─────────┼─────────┼─────┼────────┼────────┤
│ pm2-server-monit │ 2.5.2   │ N/A        │ errored │ 15      │ 0%  │ 0 B    │ ------ │
└──────────────────┴─────────┴────────────┴─────────┴─────────┴─────┴────────┴────────┘
```

pm2 version: `2.8.0`

logs:
```
~ $ pm2 logs pm2-server-monit
[TAILING] Tailing last 15 lines for [pm2-server-monit] process (change the value with --lines option)
/home/-----/.pm2/logs/pm2-server-monit-out-5.log last 15 lines:
/home/-----/.pm2/logs/pm2-server-monit-error-5.log last 15 lines:
5|pm2-serv |     at refreshMetrics (/home/-----/.pm2/node_modules/pm2-server-monit/lib/drive.js:10:3)
5|pm2-serv |     at Object.init (/home/-----/.pm2/node_modules/pm2-server-monit/lib/drive.js:100:3)
5|pm2-serv |     at /home/-----/.pm2/node_modules/pm2-server-monit/app.js:46:9
5|pm2-serv |     at Object.PMX.initModule (/home/-----/.pm2/node_modules/pm2-server-monit/node_modules/pmx/lib/pmx.js:124:12)
5|pm2-serv | TypeError: Bad argument
5|pm2-serv |     at TypeError (native)
5|pm2-serv |     at ChildProcess.spawn (internal/child_process.js:285:26)
5|pm2-serv |     at exports.spawn (child_process.js:362:9)
5|pm2-serv |     at Object.exports.execFile (child_process.js:151:15)
5|pm2-serv |     at Object.exports.exec (child_process.js:111:18)
5|pm2-serv |     at module.exports (/home/-----/.pm2/node_modules/pm2-server-monit/lib/exec.js:15:6)
5|pm2-serv |     at refreshMetrics (/home/-----/.pm2/node_modules/pm2-server-monit/lib/drive.js:10:3)
5|pm2-serv |     at Object.init (/home/-----/.pm2/node_modules/pm2-server-monit/lib/drive.js:100:3)
5|pm2-serv |     at /home/-----/.pm2/node_modules/pm2-server-monit/app.js:46:9
5|pm2-serv |     at Object.PMX.initModule (/home/-----/.pm2/node_modules/pm2-server-monit/node_modules/pmx/lib/pmx.js:124:12)

```
