### ISSUE TITLE
"TypeError: Cannot read property '0' of null" on amazon red hat linux

### ISSUE THREAD

**Issue by helios1138** [pm2-hive/pm2-server-monit#9]
error:
```
TypeError: Cannot read property '0' of null
    at /home/ec2-user/.pm2/node_modules/pm2-server-monit/lib/os.js:11:51
    at /home/ec2-user/.pm2/node_modules/pm2-server-monit/node_modules/shelljs/src/exec.js:138:7
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

os info:
```
NAME="Red Hat Enterprise Linux Server"
VERSION="7.1 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.1"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.1 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.1:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.1"
```

**Comment by Kyoshim** [comment]
Hi @helios1138 

Can you try to install the lastest version of pm2-server-monit ?
By using this command : 
```bash 
pm2 install pm2-server-monit 
```

**Comment by helios1138** [comment]
@Kyoshim same thing: http://i.imgur.com/g9v3RxM.png

**Comment by Kyoshim** [comment]
@helios1138 
Can you try the latest again ? I added a domain for stopping crashes.
I am working on a fix for displayed properly the operating system.

**Comment by helios1138** [comment]
@Kyoshim now it's working
